export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
export const GET_ALL_CHARACTERS = "GET_ALL_CHARACTERS";
export const SET_ALL_CHARACTERS = "SET_ALL_CHARACTERS";
